---
- name: nginx
  hosts: nginx
  remote_user: ubuntu
  vars:
    root: '~/chirp/packages/chirp-api-nginx'
  tasks:
    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: latest
    - name: Clean up nginx
      become: yes
      file:
        path: '/etc/nginx/sites-enabled/default'
        state: absent
    - name: Copy nginx config
      become: yes
      copy:
        src: "{{ root }}/nginx.conf"
        dest: /etc/nginx/nginx.conf
        force: yes
    - name: Copy load balancer config
      become: yes
      copy:
        src: "{{ root }}/config"
        dest: /etc/nginx/conf.d/lb.conf
        force: yes
    - name: Start nginx
      become: yes
      service:
        name: nginx
        state: restarted
