---
- name: nginx
  hosts: nginx
  remote_user: ubuntu
  tasks:
    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: latest
    - name: Clean up nginx
      become: yes
      file:
        path: '/etc/nginx/sites-enabled/default'
        state: absent
    - name: Copy load balancer config
      become: yes
      file:
        src: '/home/ubuntu/chirp/packages/chirp-api-nginx/config'
        dest: '/etc/nginx/conf.d/lb.conf'
        state: link
        force: yes
    - name: Start nginx
      become: yes
      service:
        name: nginx
        state: restarted
