- name: Webserver
  hosts: webserver
  remote_user: ubuntu
  vars:
    root: '~/chirp/packages/chirp-api'
  tasks:
    - name: Install Node.js
      become: yes
      apt:
        name: nodejs
        force_apt_get: yes
        update_cache: yes
    - name: Install npm
      become: yes
      apt:
        name: npm
        update_cache: yes
    - name: Install pm2
      become: yes
      npm:
        global: yes
        name: pm2
    - name: Install project dependencies
      npm:
        path: "{{ root }}"
    - name: Stop old process
      command: pm2 delete ws
    - name: Start new process
      command: "pm2 start npm --name ws -- start --prefix {{ root }}"
