---
- name: nginx
  hosts: nginx
  remote_user: ubuntu
  tasks:
    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: latest
    - name: git clone repo
      git:
        repo: 'git@github.com:TaskSquirrel/chirp.git'
        dest: ~/chirp
        accept_hostkey: yes
        update: yes
    - name: Start nginx
      command: nginx -c ~/chirp/packages/chirp-api-nginx/config
