- name: Webserver
  hosts: webserver
  remote_user: ubuntu
  tasks:
    - name: Install Node.js
      become: yes
      apt:
        name: nodejs
        force_apt_get: yes
        update_cache: yes
    - name: git clone repo
      git:
        repo: 'git@github.com:TaskSquirrel/chirp.git'
        dest: ~/chirp
        accept_hostkey: yes
        update: yes

